# Generated by Django 2.2 on 2019-12-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cusip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('marketSector', models.CharField(max_length=200)),
                ('securityType', models.CharField(max_length=200)),
                ('exchCode', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
                ('cusipCode', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Isin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('marketSector', models.CharField(max_length=200)),
                ('securityType', models.CharField(max_length=200)),
                ('exchCode', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sedol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('marketSector', models.CharField(max_length=200)),
                ('securityType', models.CharField(max_length=200)),
                ('exchCode', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
